name: Build and test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: |
          cargo build
      - name: Check formatting
        run: |
          cargo fmt --check
      - name: Lint
        run: |
          cargo clippy
      - name: Test
        run: |
          cargo test
